// This script will produce a crash in nvwgf2umx.dll after 3 minutes about 50% of the time.
// you must be in HMD mode on start up.

HIFI_FOLDER = "file:///C:/Users/bdavis/Git/hifi";
HIFI_SCRIPTS_FOLDER = HIFI_FOLDER + "/scripts";
HIFI_RESOURCES_FOLDER = HIFI_FOLDER + "/interface/resources";

MODEL_URLS = [
    "http://hifi-content.s3.amazonaws.com/ozan/dev/anim/standard_anims_160127/kneel.fbx",
    "http://hifi-content.s3.amazonaws.com/ozan/dev/avatars/camera_man/pod/_latest/camera_man_pod/camera_man_pod.fbx",
    "http://hifi-content.s3.amazonaws.com/Avatars/production/simple_robot/simple_robot.fbx",
    "http://mpassets.highfidelity.com/e76946cc-c272-4adf-9bb6-02cde0a4b57d-v1/DefaultStylizedFemale.fbx",
    "http://hifi-content.s3.amazonaws.com/Avatars/production/priscilla/priscilla/priscilla.fbx",
    "http://mpassets.highfidelity.com/d029ae8d-2905-4eb7-ba46-4bd1b8cb9d73-v1/Will.fbx",
    "http://hifi-content.s3.amazonaws.com/Avatars/production/matthew/shirt/matthew/matthew.fbx",
    "http://mpassets.highfidelity.com/1592e15e-c822-41aa-b314-4ef261e5d843-v1/builder-grid.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Hangar.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Grid.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Rotating-sign.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Glo-Block-beacon-glow.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Teleport-Pad.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/james/gametable-dev/assets/table/table.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Glo-Block-g.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Glo-Block-beacon.fbx",
    "http://hifi-content.s3.amazonaws.com/james/gametable-dev/assets/buttons/button-next.fbx",
    "https://hifi-content.s3.amazonaws.com/james/gametable-dev/assets/dice/dice.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Glo-wall.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Portal-Sign-Featured-2.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hat_1purple.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hat_1white.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hat_3white.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hat_2pink.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Glo-Block-r.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hat_3pink.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hatpurple.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hat_2purple.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hatwhite.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hat_1pink.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/halloween/witch hats/hat_2white.fbx",
    "https://hifi-content.s3.amazonaws.com/jimi/snail/snail_Dance2.fbx",
    "https://hifi-content.s3.amazonaws.com/jimi/snail/snail_Dance2.fbx",
    "http://hifi-production.s3.amazonaws.com/tutorials/pictureFrame/finalFrame.fbx",
    "http://hifi-content.s3.amazonaws.com/james/gametable-dev/assets/buttons/button-reset.fbx",
    "https://s3.amazonaws.com/hifi-public/tony/tablet.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Torch.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Hangar-End.fbx",
    "https://hifi-content.s3.amazonaws.com/ozan/dev/avatars/morph/F_PartyGirl/F_PartyGirl/F_PartyGirl.fbx",
    "http://hifi-content.s3.amazonaws.com/ozan/dev/anim/standard_anims_160127/kneel.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/wall_corbent.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/sandmound.fbx",
    "http://hifi-content.s3.amazonaws.com/ozan/dev/avatars/invisible_avatar/invisible_avatar/invisible_avatar.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/dev/Junkyard/hifiHenge_final.fbx",
    "http://hifi-production.s3.amazonaws.com/tutorials/pingPongGun/Pingpong-Gun-New.fbx",
    "http://mpassets.highfidelity.com/9aaf5358-9c66-4dcf-9565-e1b0a9ec500d-v1/assets/HookGun.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/barrel_redopen.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/dumptruckj.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/barrel_greenopen.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/st_weekend.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/barrel_plasticblue.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/sofastack.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Dirt-Skid.fbx",
    "https://hifi-content.s3.amazonaws.com/alan/dev/Terrain-3p.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/st_scaffold_VR.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/st_metalPlate_VR.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_noao.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/wall_corshort.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/tireclosed.fbx",
    "https://hifi-content.s3.amazonaws.com/alan/dev/Terrain-8e.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Playa/crate_noao.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/bumpercar_porange.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonsigns_2/speedys_sign.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/longvent.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/st_champagne_VR.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_red.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonSigns/rosedales.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/carstack.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/st_cabover_VR.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_lemondrop.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonsigns_2/Chesters_sign.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/st_shasta_white_VR.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/st_funkyTrailer_VR.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/treehouse_2.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Terrain-7b.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_jazmin.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/wall_corshort2.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonSigns/austinsatomiceats.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonSigns/langton_circuscasino.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_green.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/ArticulatedCrane/crane_bottom_VR.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonSigns/citronblue.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonsigns_2/penny.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/car1.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/hookshotTruss_nobase_VR.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/ArticulatedCrane/crane_top_VR_2.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/wall_corblue.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/ufoseat.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonsigns_2/hifi_circularsign.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_yellow.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/st_shasta_green_VR.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/treehouse.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/walking_guy3.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/bumpercar_rocket.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/lump1.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/TheStacks/Exports/schoolBus_reimportedIndexed.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/tire4.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/tireopen.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/tire5.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/tire_knobby.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/eric/models/Launch-Button.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/wall_cardboard.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/lump2.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/chairs/fancyThrone.fbx",
    "http://hifi-public.s3.amazonaws.com/Hackathon/LP2.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/ampytheadur/Amphitheater_HiFI.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/ferriswheel.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/barrel_redclosed.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/lump4.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/New-Moon.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/hookshot/zeppelin_hookshot_VR.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/RustyGiantRobot2.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Models/neonsigns_2/burgerdrome.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_penny.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/production/parkBots/Cicero Idle 8.fbx",
    "http://hifi-content.s3.amazonaws.com/Examples Content/production/paddleball/tballPole_VR.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Cyclone-4.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/dev/Junkyard/puebloTextured.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/seth/production/NBody/moon.fbx",
    "http://hifi-content.s3.amazonaws.com/Examples Content/production/Balloon/redBalloon.fbx",
    "http://hifi-public.s3.amazonaws.com/Hackathon/speaker.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/dieFi/bloody-cargo-container.fbx",
    "http://hifi-content.s3.amazonaws.com/caitlyn/production/elBoppo/elBoppo3_VR.fbx",
    "http://mpassets.highfidelity.com/875bcd3b-7b7d-45a1-a429-c0c6eefad95d-v1/fly.fbx",
    "http://mpassets.highfidelity.com/875bcd3b-7b7d-45a1-a429-c0c6eefad95d-v1/idle.fbx",
    "https://s3.amazonaws.com/hifi-public/marketplace/hificontent/ozan/PalmTree.fbx",
    "http://mpassets.highfidelity.com/875bcd3b-7b7d-45a1-a429-c0c6eefad95d-v1/sit_idle_talk_inplace.fbx",
    "http://mpassets.highfidelity.com/875bcd3b-7b7d-45a1-a429-c0c6eefad95d-v1/sit_idle_inplace.fbx",
    "http://mpassets.highfidelity.com/875bcd3b-7b7d-45a1-a429-c0c6eefad95d-v1/sit_down.fbx",
    "http://mpassets.highfidelity.com/875bcd3b-7b7d-45a1-a429-c0c6eefad95d-v1/talk.fbx",
    "http://hifi-public.s3.amazonaws.com/Hackathon/record player2.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/dieFi/cargo-container.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Rocks-Dolmien.fbx",
    "http://hifi-public.s3.amazonaws.com/Hackathon/boy1.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonsigns_2/lillys_signx.fbx",
    "http://hifi-content.s3.amazonaws.com/Examples Content/production/avatarAccessories/plunger/plunger2.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/trashbin.fbx",
    "http://hifi-public.s3.amazonaws.com/Hackathon/lava_lamp3.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/lump3.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_blue.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/Junkyard/Playa/billboard_stuckeys_512_2b.fbx",
    "http://hifi-content.s3.amazonaws.com/DomainContent/production/parkBots/Cicero Idle 8.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Models/neonsigns_2/candy_mountain.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/vent4.fbx",
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/Junkyard/Playa/crate_lightblue.fbx",
    "http://hifi-public.s3.amazonaws.com/viveController/ViveController.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Torch.fbx",
    "http://hifi-content.s3.amazonaws.com/alan/dev/Hangar.fbx",
    "http://mpassets.highfidelity.com/1592e15e-c822-41aa-b314-4ef261e5d843-v1/builder-grid.fbx",
    HIFI_SCRIPTS_FOLDER + "/system/assets/models/teleport-destination.fbx",
    HIFI_SCRIPTS_FOLDER + "/system/assets/models/teleport-cancel.fbx",
    HIFI_RESOURCES_FOLDER + "/meshes/being_of_light/being_of_light.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/hydra_pose_open_right.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/hydra_pose_closed_right.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/hydra_pose_open_left.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/hydra_pose_closed_left.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/idle.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/talk.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/walk_short_fwd.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/walk_fwd.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/run_fwd.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/idle_to_walk.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/walk_short_bwd.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/walk_bwd.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/jump_land.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/jump_standing_land.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/jump_in_air.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/jump_standing_apex.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/jump_takeoff.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/jump_standing_takeoff.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/fly.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/side_step_right.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/side_step_short_right.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/side_step_left.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/side_step_short_left.fbx",
    HIFI_RESOURCES_FOLDER + "/avatar/animations/turn_left.fbx",
];

MyAvatar.position = {x: -2.3, y: 0.6, z: 12.0};
MyAvatar.orientation = {x: 0, y: 0, z: 0, w: 1};

exportObj = [];

MODEL_URLS.forEach(function (url) {
    exportObj.push({
        modelURL: url,
        type: "Model"
    });
});

print(JSON.stringify(exportObj));


MODEL_URLS.forEach(function (url) {
    //Overlays.addOverlay("model", {url: url, visible: true });
});
